Added support for PG13
yugabyte/yb-db-migration pull request #128
Opened 2022-05-17 11:32 UTC by rahulb-yb

2022-05-18 07:17 UTC, amit-yb requested changes
All you have to do is skip the lines having `"SET default_table_access_method"` prefix. Don't make it "PG13" aware. Tomorrow, there will many other version and cases.

2022-05-19 04:00 UTC, amit-yb commented on yb_migrate/src/srcdb/pg_dump_extract_schema.go
> +func isPG13statement(line string) bool {
Rename this function to `shouldSkipLine(line string)`.

2022-05-19 18:16 UTC, sanyamsinghal approved these changes
LGTM

2022-05-20 07:03 UTC, amit-yb approved these changes

2022-05-20 07:22 UTC, merged